2017_MVC_Wardrobe/Models/Wardrobe_Items.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_MVC_Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wardrobe_Items
    {
        public int ItemID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public string Color { get; set; }
        public string Season { get; set; }
        public string Occasion { get; set; }
    
        public virtual Categorty_Type Categorty_Type { get; set; }
    }
}

2017_MVC_Wardrobe/Controllers/Wardrobe_ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _2017_MVC_Wardrobe.Models;

namespace _2017_MVC_Wardrobe.Controllers
{
    public class Wardrobe_ItemsController : Controller
    {
        private Wardrobe2017Entities db = new Wardrobe2017Entities();

        // GET: Wardrobe_Items
        public ActionResult Index()
        {
            var wardrobe_Items = db.Wardrobe_Items.Include(w => w.Categorty_Type);
            return View(wardrobe_Items.ToList());
        }

        // GET: Wardrobe_Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wardrobe_Items wardrobe_Items = db.Wardrobe_Items.Find(id);
            if (wardrobe_Items == null)
            {
                return HttpNotFound();
            }
            return View(wardrobe_Items);
        }

        // GET: Wardrobe_Items/Create
        public ActionResult Create()
        {
            ViewBag.TypeID = new SelectList(db.Categorty_Type, "TypeId", "Categories");
            return View();
        }

        // POST: Wardrobe_Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemID,TypeID,Name,Photo,Color,Season,Occasion")] Wardrobe_Items wardrobe_Items)
        {
            if (ModelState.IsValid)
            {
                db.Wardrobe_Items.Add(wardrobe_Items);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TypeID = new SelectList(db.Categorty_Type, "TypeId", "Categories", wardrobe_Items.TypeID);
            return View(wardrobe_Items);
        }

        // GET: Wardrobe_Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wardrobe_Items wardrobe_Items = db.Wardrobe_Items.Find(id);
            if (wardrobe_Items == null)
            {
                return HttpNotFound();
            }
            ViewBag.TypeID = new SelectList(db.Categorty_Type, "TypeId", "Categories", wardrobe_Items.TypeID);
            return View(wardrobe_Items);
        }

        // POST: Wardrobe_Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemID,TypeID,Name,Photo,Color,Season,Occasion")] Wardrobe_Items wardrobe_Items)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wardrobe_Items).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeID = new SelectList(db.Categorty_Type, "TypeId", "Categories", wardrobe_Items.TypeID);
            return View(wardrobe_Items);
        }

        // GET: Wardrobe_Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wardrobe_Items wardrobe_Items = db.Wardrobe_Items.Find(id);
            if (wardrobe_Items == null)
            {
                return HttpNotFound();
            }
            return View(wardrobe_Items);
        }

        // POST: Wardrobe_Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wardrobe_Items wardrobe_Items = db.Wardrobe_Items.Find(id);
            db.Wardrobe_Items.Remove(wardrobe_Items);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

2017_MVC_Wardrobe/Views/Wardrobe_Items/Create.cshtml
@model _2017_MVC_Wardrobe.Models.Wardrobe_Items

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Wardrobe_Items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, "TypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Season, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Season, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Season, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

2017_MVC_Wardrobe/Views/Wardrobe_Items/Delete.cshtml
@model _2017_MVC_Wardrobe.Models.Wardrobe_Items

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Wardrobe_Items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Season)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Season)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occasion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occasion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categorty_Type.Categories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorty_Type.Categories)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

2017_MVC_Wardrobe/Views/Wardrobe_Items/Details.cshtml
@model _2017_MVC_Wardrobe.Models.Wardrobe_Items

@{
    ViewBag.Title = "Details";
}



<h1>Details</h1>
<div class="container">
    <div class="row">


        <br />

        <div class="gallery_product col-lg-12 col-md-12 col-sm-12 col-xs-12 filter hdpe">
            
            <div class="thumbnail">
                <img src="@Url.Content(@Model.Photo)" alt="@Model.Occasion" />
                <div id="detail_caption" class="caption">
                   
                    <h3>@Html.DisplayNameFor(model => model.Name):@Html.DisplayFor(model => model.Name)</h3>
                    <h3>@Html.DisplayNameFor(model => model.Color):@Html.DisplayFor(model => model.Color)</h3>
                    <h3>@Html.DisplayNameFor(model => model.Season):@Html.DisplayFor(model => model.Season)</h3>
                    <h3>@Html.DisplayNameFor(model => model.Occasion):@Html.DisplayFor(model => model.Season)</h3>
                    <h3>@Html.DisplayNameFor(model => model.Categorty_Type.Categories):@Html.DisplayFor(model => model.Categorty_Type.Categories)</h3>
                  

                </div>
            </div>
        </div>

        
            </div>
        </div>

      
@*<div>
    <h2>Wardrobe_Items</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            <img src="@Url.Content(@Model.Photo)" alt="@Model.Occasion" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Season)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Season)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occasion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occasion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categorty_Type.Categories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorty_Type.Categories)
        </dd>

    </dl>
</div>*@
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

2017_MVC_Wardrobe/Views/Wardrobe_Items/Edit.cshtml
@model _2017_MVC_Wardrobe.Models.Wardrobe_Items

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Wardrobe_Items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, "TypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Season, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Season, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Season, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

2017_MVC_Wardrobe/Views/Wardrobe_Items/Index.cshtml
@model IEnumerable<_2017_MVC_Wardrobe.Models.Wardrobe_Items>

@{
    ViewBag.Title = "Index";
}

<h1>JD warDrobe</h1>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="container">
    <div class="row">


        <br />

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-12 filter hdpe">

            <div class="thumbnail">
                <img id="kyrie" src="~/Content/Photos/Kyrie_Jersy.jpg" class="img-responsive">
                <div class="caption">
                    <h1>TOPS</h1>

                    <button>
                        @Html.ActionLink("Details", "Details/1", "Wardrobe_Items")
                    </button>

                </div>
            </div>
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-12 filter hdpe">
            <div class="thumbnail">
                <img id="indians" src="~/Content/Photos/Indians_Coat.jpg" class="img-responsive">
                <div class="caption">
                    <h1>TOPS</h1>

                    <button>
                        @Html.ActionLink("Details", "Details/2", "Wardrobe_Items")
                    </button>

                </div>
            </div>
        </div>
        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-12 filter hdpe">
            <div class="thumbnail">
                <img id="cavs" src="~/Content/Photos/CavsPants.jpg" class="img-responsive">
                <div class="caption">
                    <h1>BOTTOMS</h1>

                    <button>
                        @Html.ActionLink("Details", "Details/3", "Wardrobe_Items")
                    </button>

                </div>
            </div>
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-12 filter hdpe">
            <div class="thumbnail">
                <img id="browns" src="~/Content/Photos/Browns_PJPants.jpg" class="img-responsive">
                <div class="caption">
                    <h1>BOTTOMS</h1>

                    <button>
                        @Html.ActionLink("Details", "Details/4", "Wardrobe_Items")
                    </button>

                </div>
            </div>
        </div>
         <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-12 filter hdpe">
            <div class="thumbnail">
                <img id="airmax" src="~/Content/Photos/AirMax.jpg" class="img-responsive">
                <div class="caption">
                    <h1>SHOES</h1>

                    <button>
                        @Html.ActionLink("Details", "Details/5", "Wardrobe_Items")
                    </button>

                </div>
            </div>
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-12 filter hdpe">
            <div class="thumbnail">
                <img id="addidas" src="~/Content/Photos/Addidas.jpg" class="img-responsive">
                <div class="caption">
                    <h1>SHOES</h1>

                    <button>
                        @Html.ActionLink("Details", "Details/6", "Wardrobe_Items")
                    </button>

                </div>
            </div>
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-12 filter hdpe">
            <div class="thumbnail">
                <img id="gear2" src="~/Content/Photos/Gear2.jpg" class="img-responsive">
                <div class="caption">
                    <h1>ACCESSORIES</h1>

                    <button>
                        @Html.ActionLink("Details", "Details/7", "Wardrobe_Items")
                    </button>
                    


                </div>
            </div>
        </div>

        <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-12 filter hdpe">
            <div class="thumbnail">
                <img id="movado" src="~/Content/Photos/Movado.jpg" class="img-responsive">
                <div class="caption">
                    <h1>ACCESSORIES</h1>

                    <button>
                        @Html.ActionLink("Details", "Details/8", "Wardrobe_Items")
                    </button>

                </div>
            </div>
        </div>
    </div>
</div>

@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Season)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Occasion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categorty_Type.Categories)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Photo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Season)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Occasion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categorty_Type.Categories)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ItemID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ItemID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ItemID })
        </td>
    </tr>
}

</table>*@